#version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sio-postgres
    environment:
      POSTGRES_USER: sio_user
      POSTGRES_PASSWORD: sio_password
      POSTGRES_DB: sio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: sio-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: sio_user
      DB_PASS: sio_password
      DB_NAME: sio_db
      JWT_SECRET: "chiave_segreta_super_sicura_per_il_corso_segretissimissima"
      AUTH_ENABLED: "false"
    depends_on:
      - db
    restart: always

  fe-sio:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${SVI_VERSION:-latest}
    container_name: sio-fe-sio
    environment:
      APP_ENV: "SVI"
      APP_VERSION: "${SVI_VERSION}"

  # AMBIENTE PRODUZIONE (BLUE)
  fe-prod:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${PROD_VERSION:-latest}
    container_name: sio-fe-prod
    environment:
      APP_ENV: "PROD"
      APP_VERSION: "${PROD_VERSION}"

  fe-test:
    build:
      context: ./his-afp
      dockerfile: Dockerfile
    image: his-afp:${TEST_VERSION:-latest}
    container_name: sio-fe-test
    environment:
      APP_ENV: "TEST"
      APP_VERSION: "${TEST_VERSION}"

  gateway:
    image: nginx:alpine
    container_name: sio-gateway
    ports:
      - "80:80"
      - "8080:8080"
      - "8999:8999"
    volumes:
      - ./gateway:/etc/nginx/conf.d/:ro
    depends_on:
      - fe-sio
      - fe-prod
      - fe-test
    restart: always

volumes:
  pg_data:
