upstream backend_api {
    # Default route: Blue backend.
    server sio-backend-blue:3000;
    # To switch to Green, replace the line above with:
    # server sio-backend-green:3000;
}

# AMBIENTE PROD
server{
    listen 80;
    server_name localhost;
    location / {
        proxy_pass http://fe-prod:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend_api;
    }
}

# AMBIENTE TEST
server{
    listen 8080;
    location / {
        proxy_pass http://fe-test:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend_api;
    }
}

# AMBIENTE SVI
server{
    listen 8999;
    location / {
        proxy_pass http://fe-sio:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend_api;
    }
}
